name: Test On macOS

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

jobs:
  dotnet-tests:
    name: C# Tests (macOS)
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout latest commit including build artifacts
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - run: dotnet restore ./src/PSSqliteRoH.Sqlite/PSSqliteRoH.Sqlite.csproj
      - run: dotnet build ./src/PSSqliteRoH.Sqlite/PSSqliteRoH.Sqlite.csproj --configuration Release --no-restore
      - run: dotnet test ./src/PSSqliteRoH.Sqlite.Tests/ --no-build --verbosity normal
