name: Test On Windows

on:
  workflow_run:
    # Workflow that triggers this workflow
    workflows: ["Build"]
    types:
      - completed

jobs:
  test-windows:
    name: Windows Tests (${{ matrix.shell }})
    runs-on: windows-latest
    # Run only when triggering workflow was successfull
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        shell:
          - pwsh
          - powershell

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # C# Tests
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore C# dependencies
        run: dotnet restore ./src/PSSqliteRoH.Sqlite/PSSqliteRoH.Sqlite.csproj

      - name: Build C# project
        run: dotnet build ./src/PSSqliteRoH.Sqlite/PSSqliteRoH.Sqlite.csproj --configuration Release --no-restore

      - name: Run C# tests
        run: dotnet test ./src/PSSqliteRoH.Sqlite.Tests/ --no-build --verbosity normal

      # PESTER Tests
      - name: Install Pester
        run: Install-Module Pester -Force -Scope CurrentUser

      - name: Run Pester tests
        run: Invoke-Pester -Path ./tests/ -Output Detailed -EnableExit
