name: Test On macOS pwsh

on:
  workflow_dispatch:

jobs:
 
  pester-tests:
    name: Pester Tests (macOS pwsh)
    runs-on: macos-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Install Pester
        run: Install-Module Pester -Force -Scope CurrentUser

      # - name: Run Pester tests
      #   run: Invoke-Pester -Path ./tests/ -Output Detailed

      - name: Get location
        run: (Get-Location).Path

      - name: Get child items
        run: (Get-ChildItem -Path (Get-Location).Path -Recurse).FullName

      - name: Find PS Module
        run: (Get-ChildItem -Path (Get-Location).Path -Recurse | Where-Object {$_.Name -like "*PSModule*"}).FullName
