name: Test On macOS

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:

  dotnet-tests:
    name: C# Tests (macOS)
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore C# dependencies
        run: dotnet restore ./src/PSSqliteRoH.Sqlite/PSSqliteRoH.Sqlite.csproj

      - name: Build C# project
        run: dotnet build ./src/PSSqliteRoH.Sqlite/PSSqliteRoH.Sqlite.csproj --configuration Release --no-restore

      - name: Run C# tests
        run: dotnet test ./src/PSSqliteRoH.Sqlite.Tests/ --no-build --verbosity normal

  pester-tests:
  name: Pester Tests (macOS pwsh)
  runs-on: macos-latest
  needs: dotnet-tests

  defaults:
    run:
      shell: pwsh

  steps:
    - name: Checkout full repo including build artifacts
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Pester
      run: Install-Module Pester -Force -Scope CurrentUser

    - name: Import module
      run: Import-Module "$PWD/PSSqliteRoH.psm1" -Force

    - name: Run Pester tests
      run: Invoke-Pester -Path ./tests/ -Output Detailed

